version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    container_name: goanalisis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: unless-stopped

  # 2. Redis
  redis:
    image: redis:7-alpine
    container_name: goanalisis_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  # 3. API (FastAPI)
  api:
    build: .
    container_name: goanalisis_api
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app:z
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # 4. Worker (Celery + Selenium) - RENOMBRADO PARA CORREGIR ERROR
  celery_node:
    build: .
    container_name: goanalisis_celery_node
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=3
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    # AUMENTO DE MEMORIA PARA EVITAR CRASH DE CHROME
    shm_size: '2gb' 
    restart: unless-stopped
    
  # 5. Beat (Scheduler)
  celery_beat:
    build: .
    container_name: goanalisis_celery_beat
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    command: celery -A tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  postgres_data:
